CLASS ziacl010_airplane_poly DEFINITION ABSTRACT
  PUBLIC
 " FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.


    METHODS:
      airplane_type ABSTRACT
        RETURNING VALUE(rv_airplane_type) TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ziacl010_airplane_poly IMPLEMENTATION.
ENDCLASS.
